### ISSUE TITLE
Could not connect to websocket

### ISSUE THREAD

**Issue by lukasz-kuch** [arnoudkooi/sn-scriptsync#54]
I have the latest version of vs code and sn-scriptsync. SN Utils chrome extension - VS Script Sync is enabled. SN-scriptsync is running, unfortunately, the connection failed. Cannot also access  http://localhost:1978 - error not found.

**Comment by arnoudkooi** [comment]
Do you see _Upgrade Required_ when opening http://localhost:1978/ in browser, soes the helper tab open, console errors?

**Comment by lukasz-kuch** [comment]
When opening  http://localhost:1978 I get "This site can’t be reached". Helper tab open with following messegaes: "Could not connect to WebSocket. Check if VS Code is running and wait for connection or reload the page". 
Console errror from browser: "scriptsync.js:37 WebSocket connection to 'ws://127.0.0.1:1978/' failed: "

**Comment by arnoudkooi** [comment]
Are you sure it is running in VS Code, look at the bottom to check, click on it to start stop 
![image](https://user-images.githubusercontent.com/840781/119225520-7f9a1600-bb04-11eb-915f-48f658b0ea51.png)

**Comment by lukasz-kuch** [comment]
Yes, it looks the same. I've used it some time ago and it worked fine. For few days it didn't work at all

**Comment by lukasz-kuch** [comment]
![image](https://user-images.githubusercontent.com/48534352/119225802-5d08fc80-bb06-11eb-9e53-2b7d16a9c5b6.png)

**Comment by arnoudkooi** [comment]
Maybe a reboot, we could do a quick zoom call if you want: https://servicenow.zoom.us/my/arnoudkooi

**Comment by arnoudkooi** [comment]
Please do a reboot, reinstall of the extension and check the VS Code terminal for errors. We can setup a call to troubleshoot as well

**Comment by lukasz-kuch** [comment]
Please sow terminal error below:
`Error: listen EACCES: permission denied 0.0.0.0:1977
at Server.setupListenHandle [as _listen2] (net.js:1301:21)
at listenInCluster (net.js:1366:12)
at Server.listen (net.js:1452:7)
at Function.listen (c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\node_modules\express\lib\application.js:618:24)
at startServers (c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\extension.js:217:25)
at c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\extension.js:100:9
at E._executeContributedCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)
at E._doExecuteCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107077)
at E.executeCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:106983)
at Object.executeCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:96:21346)
at c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\extension.js:51:29
at E._executeContributedCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)
at E.$executeContributedCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:108370)
at l._doInvokeHandler (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
at l._invokeHandler (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
at l._receiveRequest (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)
at l._receiveOneMessage (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
at fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
at S.fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764
at fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
at S.fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
at t._receiveMessage (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641
at fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
at acceptChunk (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210
at Socket.v (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)
at Socket.emit (events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
Error: listen EACCES: permission denied 0.0.0.0:1978
at Server.setupListenHandle [as _listen2] (net.js:1301:21)
at listenInCluster (net.js:1366:12)
at Server.listen (net.js:1452:7)
at new WebSocketServer (c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\node_modules\ws\lib\websocket-server.js:76:20)
at startServers (c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\extension.js:219:11)
at c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\extension.js:100:9
at E._executeContributedCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)
at E._doExecuteCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107077)
at E.executeCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:106983)
at Object.executeCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:96:21346)
at c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\extension.js:51:29
at E._executeContributedCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:107932)
at E.$executeContributedCommand (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:108370)
at l._doInvokeHandler (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12836)
at l._invokeHandler (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:12520)
at l._receiveRequest (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:11187)
at l._receiveOneMessage (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:9973)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:91:8074
at fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
at S.fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:29764
at fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
at S.fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15497)
at t._receiveMessage (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20755)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17641
at fire (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1836)
at acceptChunk (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12862)
at c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12210
at Socket.v (c:\Users\KUCHARSKIL\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:106:13195)
at Socket.emit (events.js:315:20)
at addChunk (internal/streams/readable.js:309:12)
at readableAddChunk (internal/streams/readable.js:284:9)
at Socket.Readable.push (internal/streams/readable.js:223:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
at Object.copyFile (fs.js:1972:10)
at Object.t.<computed> [as copyFile] (electron/js2c/asar_bundle.js:5:2242)
at c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\out\ExtensionUtils.js:26:16
at c:\Users\KUCHARSKIL\.vscode\extensions\arnoudkooicom.sn-scriptsync-1.9.9\node_modules\mkdirp\index.js:49:26
at FSReqCallback.oncomplete (fs.js:184:5)`

**Comment by arnoudkooi** [comment]
Seems to be an permission issue, do you have full rights? Could you try run vs code as an admin?

**Comment by lukasz-kuch** [comment]
I've tried with admin permission on vs code but it didn't helped

**Comment by lukasz-kuch** [comment]
Issue solved. The ports1977-1978 belonged to `Protocol tcp Port Exclusion Ranges`. 
Checked using Powershell command:
 ```powershell
netsh interface ipv4 show excluded port range protocol=tcp
````
I've free the ports using Powershell command:
```powershell
net stop winnat
````

**Comment by arnoudkooi** [comment]
Glad it's resolved. Did you remove the comment with the solution?

**Comment by lukasz-kuch** [comment]
Accidently removed ;) 
The solution worked for me below: 
The ports1977-1978 belonged to `Protocol TCP Port Exclusion Ranges`. 
Checked using Powershell command:
 ```powershell
netsh interface ipv4 show excluded port range protocol=tcp
````
I've free the ports using Powershell command:
```powershell
net stop winnat
````

**Comment by iCode18** [comment]
I have the almost same problem. In my case and using Mac, the helper tab does not open anymore. I get the widget in VS Code by clicking the save icon but when I do save in VS Code. I get this: "No WebSocket connection. Please open SN Utils helper tab in a browser via slashcommand /token"
I tried to find what using port 1977 and kill it, but it didn't help.

**Comment by arnoudkooi** [comment]
@iCode18 there is a problem at the moment, please see [this issue](https://github.com/arnoudkooi/ServiceNow-Utils/issues/211) that describes a workaround.

**Comment by iCode18** [comment]
> @iCode18 there is a problem at the moment, please see [this issue](https://github.com/arnoudkooi/ServiceNow-Utils/issues/211) that describes a workaround.

Thanks, it is working now with the workaround solution but not the auto-refresh at preview window. 
I know that you're working on a permanent fix, but I would just inform you about the preview issue as well.

**Comment by arnoudkooi** [comment]
The fix is now published [upgrade instruction](https://twitter.com/sn_utils/status/1142888825011789827) can you try and let me know?

**Comment by arnoudkooi** [comment]
You need to do a full page refresh before it will work
